FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir flask pillow
RUN pip install --no-cache-dir torch torchvision --extra-index-url https://download.pytorch.org/whl/cpu

COPY app.py .
COPY templates ./templates

# Create directory for model loading
RUN mkdir -p /mnt/model

EXPOSE 5000

CMD ["python", "app.py"]
